### ISSUE TITLE
Hovers

### ISSUE THREAD

**Issue by MatiRojass** [Arqueik/Mercadoliebre-render#2]
Cumple con todos los items correctamente aunque hay algunos detalles.

- Falta que aparezca la **descripcion de los articulos** al hacerles hover y tambien la **animacion de rotar** el camion verde
- Los **iconos del footer** no cambian de color al hacerle hover

Despues de eso, esta todo bien hecho y funciona correctamente

**Comment by Arqueik** [comment]
Solucionado.
